.\"
.\" Copyright (c) 2019 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 18, 2019
.Dt NSYSCTL 8
.Os
.Sh NAME
.Nm nsysctl
.Nd get or set system state
.Sh SYNOPSIS
.Nm
.Op Fl -libxo Ar opts Op Fl r Ar tagname
.Op Fl DdFIGgilNpqTtWy Op V|v Op h Op b|o|x
.Op Fl e Ar sep
.Op Fl B Ar bufsize
.Op Fl f Ar filename
.Ar name Ns Op = Ns Ar value
.Ar ...
.Nm
.Op Fl -libxo Ar opts Op Fl r Ar tagroot
.Op Fl DdFGgIlNpqSTtWy Op V|v Op h Op b|o|x
.Op Fl e Ar sep
.Op Fl B Ar bufsize
.Fl A|a|X
.Sh DESCRIPTION
The systems maintains a
.Dq Management Information Base
.Pq Dq MIB
of properties.
The
.Nm
tool can get the value and allows users with appropriate
privilege to set a property of the system.
.Pp
The output is explicitly indicated by the options,
see COMPATIBILITY for a comparison with
.Xr sysctl 8 .
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl -libxo Ar options
Generate output via libxo(3) in a selection of different human
and machine readable formats.
See xo_parse_args(3)
.It Fl A
Equivalent to
.Fl a Fl o .
.It Fl a
Display all states.
.It Fl b
Print value in binary format.
.It Fl B Ar bufsize
use a buffer of <bufsize> bytes.
.It Fl D
Equivalent to
.Fl d Fl F Fl l Fl m Fl N Fl t Fl v Fl y .
.It Fl d
Show state description.
.It Fl e Ar sep
Use <sep> as separator.
.It Fl F
Display format string.
.It Fl f Ar filename
Load states to get or set from <filename>.
.It Fl G
Show true-flags.
.It Fl g
Print flags.
.It Fl h
Try to show values in a human-friendly format.
.It Fl I
Show Internal nodes, default only leaves.
.It Fl i
Ignore unknown state.
.It Fl l
Display label.
.It Fl N
Print name.
.It Fl o
Show value in hex format until 16 bytes.
.It Fl p
Display [property-name]: property-value.
.It Fl q
Avoid to show some warning.
.It Fl r Ar tagroot
Specify a <tagroot> with libxo.
.It Fl S
Display magical kernel states.
.It Fl T
Show only variables that are settable via loader.
.It Fl t
Print type.
.It Fl V
Show value, if value is not
.Dq showable
hidden the state.
.It Fl v
Display value.
.It Fl W
Display only writable variables that are not statistical.
.It Fl X
Equivalent to
.Fl a Fl x .
.It Fl x
Print value in hex format.
.It Fl y
Show id.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To get the hostname:
.Pp
.Dl "nsysctl -Nv kern.hostname"
.Pp
To set the hostname:
.Pp
.Dl "nsysctl kern.hostname=myBSD"
.Pp
Dump all info about a state:
.Pp
.Dl "nsysctl -Dp -e ', '  kern.ostype"
.Pp
Dump all info about a state in xml format:
.Pp
.Dl "nsysctl --libxo=xml,pretty -r ROOT-NAME -D kern.ostype"
.Sh COMPATIBILITY
.Bd -literal -offset indent -compact
/sbin/sysctl           /usr/local/sbin/nsysctl
% sysctl    "name"     % nsysctl -Nv "name"
% sysctl -N "name"     % nsysctl -N  "name"
% sysctl -n "name"     % nsysctl -v  "name"
% sysctl -d "name"     % nsysctl -Nd "name"
% sysctl -a            % nsysctl -NVa
% sysctl -aN           % nsysctl -aN
% sysctl -ad           % nsysctl -aNd
% sysctl -at           % nsysctl -aNt
% sysctl -ao           % nsysctl -aNVo
% sysctl -ax           % nsysctl -aNx
.Ed
.Sh SEE ALSO
.Xr sysctl 3 ,
.Xr sysctlmibinfo 3 ,
.Xr sysctl 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 13.0 .
.Sh AUTHORS
The
.Nm
utility and this manual page were written by
.An Alfonso Sabato Siciliano
.Aq Mt alf.siciliano@gmail.com
