.\"
.\" Copyright (c) 2019-2021 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 30, 2021
.Dt NSYSCTL 8
.Os
.Sh NAME
.Nm nsysctl
.Nd get or set system state
.Sh SYNOPSIS
.Nm
.Op Fl -libxo Ar options Op Fl r Ar tagroot
.Op Fl DdFGgHIilNnOpqTtW
.Op Fl V | v Op Cm h Op Cm b | o | x
.Op Fl B Ar bufsize
.Op Fl e Ar sep
.Op Fl f Ar filename
.Ar name Ns Op = Ns Ar value Ns Op , Ns Ar value
.Ar ...
.Nm
.Op Fl -libxo Ar options Op Fl r Ar tagroot
.Op Fl DdFGgHIklNnOpqSTtW
.Op Fl V | v Op Cm h Op Cm b | o | x
.Op Fl B Ar bufsize
.Op Fl e Ar sep
.Fl A | a | X
.Sh DESCRIPTION
The
.Nm nsysctl
utility can get or set the state of the System at run time.
The System exposes the available parameters as objects of a
.Dq Management Information Base
.Pq MIB ,
.Nm nsysctl
can explore the MIB, print the properties of an object, get or set its value and
show the output in human and machine readable formats.
.Pp
.Nm nsysctl
requires the
.Xr sysctlinfo 4
interface.
To load the required kernel module at boot time, place the following line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
sysctlinfo_load="YES"
.Ed
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl -libxo Ar options
Generate output via libxo(3) in a selection of different human
and machine readable formats.
See xo_parse_args(3)
.It Fl A
Equivalent to
.Fl a Fl V Fl o .
.It Fl a
Display every object.
.It Fl b
Print value in binary format.
.It Fl B Ar <bufsize>
use a buffer of
.Ar <bufsize>
bytes.
.It Fl D
Equivalent to
.Fl d Fl F Fl G Fl g Fl l Fl N Fl O Fl t Fl v .
.It Fl d
Show description.
.It Fl e Ar <sep>
Use
.Ar <sep>
as separator.
.It Fl F
Display format string.
.It Fl f Ar <filename>
Load objects to get or set from
.Ar <filename> .
.It Fl G
Show true-flags.
.It Fl g
Print flags.
.It Fl H
Show if the object has a handler.
.It Fl h
Try to show values in a human-friendly format.
.It Fl I
Show internal nodes, only leaves are printed by default.
.It Fl i
Ignore unknown objects.
.It Fl k
Show object with
.Dv SKIP
flag with
.Fl a .
.It Fl l
Display aggregation label.
.It Fl m
Alias for
.Fl S .
.It Fl N
Print name.
.It Fl n
Hide name.
.It Fl O
Display OID.
.It Fl o
Show value in hex format until 16 bytes.
.It Fl p
Display [property-name]: property-value.
.It Fl q
Avoid to show some warning.
.It Fl r Ar <tagroot>
Specify a
.Ar <tagroot>
with libxo.
.It Fl S
Display also the
.Dq sysctl.*
subtree with
.Fl a .
.It Fl T
Show only objects that are settable via loader.
.It Fl t
Print type.
.It Fl V
Show value, if value is not
.Dq showable
hidden the object.
.It Fl v
Display value.
.It Fl W
Display only writable objects that are not statistical.
.It Fl X
Equivalent to
.Fl a Fl V Fl x .
.It Fl x
Print value in hex format.
.It Fl y
Alias for
.Fl O .
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To get the value of hostname:
.Pp
.Dl "nsysctl -Nv kern.hostname"
.Pp
To set the value of hostname:
.Pp
.Dl "nsysctl kern.hostname=myBSD"
.Pp
Print all info about an object:
.Pp
.Dl "nsysctl -Dp -e ', '  kern.ostype"
.Pp
Print all info about an object in xml:
.Pp
.Dl "nsysctl --libxo=xml,pretty -r 'ROOT-NAME' -D kern.ostype"
.Sh COMPATIBILITY
.Bd -literal -offset indent -compact
/sbin/sysctl             /usr/local/sbin/nsysctl
% sysctl    name=value   % nsysctl -Nv name=value
% sysctl    name         % nsysctl -Nv name
% sysctl -d name         % nsysctl -Nd name
% sysctl -e name         % nsysctl -Nv -e ‘=’ name
% sysctl -N name         % nsysctl -N name
% sysctl -n name         % nsysctl -v name
% sysctl -t name         % nsysctl -Nt name
% sysctl -a              % nsysctl -aNV
% sysctl -aN             % nsysctl -aIKN
% sysctl -an             % nsysctl -aV
% sysctl -ad             % nsysctl -aIKNd
% sysctl -at             % nsysctl -aIKNt
% sysctl -ao             % nsysctl -aNVo
% sysctl -ax             % nsysctl -aNVx
% sysctl -A              % nsysctl -AN
% sysctl -X              % nsysctl -XN
.Ed
.Sh SEE ALSO
.Xr sysctl 3 ,
.Xr sysctlmibinfo2 3 ,
.Xr xo_parse_args 3 ,
.Xr sysctlinfo 4 ,
.Xr sysctl 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 13.0 .
.Sh AUTHORS
.Nm
was written by
.An Alfonso Sabato Siciliano
.Aq Mt alf.siciliano@gmail.com
