.\"
.\" Copyright (c) 2019 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 25, 2019
.Dt NSYSCTL 8
.Os
.Sh NAME
.Nm nsysctl
.Nd get or set kernel state
.Sh SYNOPSIS
.Nm
.Op Fl -libxo Ar opts Op Fl r Ar tagname
.Op Fl DdFIilmNpqTtWy Op V|v Op h Op b|o|x
.Op Fl e Ar sep
.Op Fl B Ar bufsize
.Op Fl f Ar filename
.Ar name Ns Op = Ns Ar value
.Ar ...
.Nm
.Op Fl -libxo Ar opts Op Fl r Ar tagname
.Op Fl DdFIlmNpqSTtWy Op V|v Op h Op b|o|x
.Op Fl e Ar sep
.Op Fl B Ar bufsize
.Fl A|a|X
.Sh DESCRIPTION
The systems maintains a
.Dq Management Information Base
.Pq Dq MIB
of kernel states.
The
.Nm
tool can get the value and allows users with appropriate
privilege to set kernel state.
.Pp
nsysctl shows only the information explicitly indicated by the options
(see COMPATIBILITY for a comparison with
.Xr sysctl 8 .
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl -libxo Ar options
Generate output via libxo(3) in a selection of different human
and machine readable formats.
See xo_parse_args(3)
.It Fl A
[DOC]
.It Fl a
[DOC]
.It Fl b
[DOC]
.It Fl B Ar bufsize
[DOC]
.It Fl D
[DOC]
.It Fl d
[DOC]
.It Fl e Ar sep
[DOC]
.It Fl F
[DOC]
.It Fl f Ar filename
[DOC]
.It Fl h
[DOC]
.It Fl I
[DOC]
.It Fl i
[DOC]
.It Fl l
[DOC]
.It Fl m
[DOC]
.It Fl N
[DOC]
.It Fl o
[DOC]
.It Fl p
[DOC]
.It Fl q
[DOC]
.It Fl r Ar tagname
[DOC]
.It Fl S
[DOC]
.It Fl T
[DOC]
.It Fl t
[DOC]
.It Fl V
[DOC]
.It Fl v
[DOC]
.It Fl W
[DOC]
.It Fl X
[DOC]
.It Fl x
[DOC]
.It Fl y
[DOC]
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To get the hostname:
.Pp
.Dl "nsysctl -Nv kern.hostname"
.Pp
To set the hostname:
.Pp
.Dl "nsysctl kern.hostname=myBSD"
.Pp
Dump all info about a state:
.Pp
.Dl "nsysctl -NlydtmFv kern.ostype"
.Pp
Dump all info about a state in xml format:
.Pp
.Dl "nsysctl --libxo=xml,pretty -r -NlydtmFv kern.ostype"
.Sh COMPATIBILITY
The
.Fl w
option has been deprecated and is silently ignored.
.Pp
% sysctl
.Ar name
.Pp
.Dl % nsysctl -Nv Ar name
.Pp
% sysctl -a:
.Pp
.Dl % nsysctl -NVa
.Pp
% sysctl -na:
.Pp
.Dl % nsysctl Va
.Sh SEE ALSO
.Xr sysctl 3 ,
.Xr sysctlmibinfo 3 ,
.Xr loader.conf 5 ,
.Xr sysctl.conf 5
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 13.0 .
.Sh AUTHORS
The
.Nm
utility and this manual page were written by
.An Alfonso S. Siciliano Aq Mt alf.siciliano@gmail.com
.Sh BUGS
%
.Nm
libxo=xml debug.witness.fullgraph -> segmentation fault
