# $FreeBSD$

PORTNAME=	nsysctl
DISTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	gitlab.com/alfix/nsysctl

MAINTAINER=	alfix86@gmail.com
COMMENT=	rewritten sysctl with libxo and extra options

.include <bsd.port.mk>
